### PR TITLE
Add destructivechanges

### PR DESCRIPTION
**Pull request by jasonhalpern**
Verifies if there are constructive or destructive changes to deploy and handles both.

### CODE REVIEW

**Comment by jasonhalpern** [comment]
@ricka Can you put another set of eyes on this, and if good, mark it as the v1 tag? Turns out the "new" SF CLI behaves a little differently with regards to destructive changes (deletes) so now the code checks to see if there are any constructive changes (handles if there are ONLY deletes), destructive changes, or both, and calls the CLI appropriately.

**Comment by ricka** [comment]
@jasonhalpern Question on the deployment...if the destructive changes file is empty, is there any harm in us sending along the "empty" destructive changes?

Additionally, grep here is the quick and dirty and PROBABLY is fine, but whenever there's an XML/HTML structure to something, I prefer to have a parser involved and look for the hierarchy tree. Maybe something like https://github.com/marketplace/actions/get-xml-info

**Comment by jasonhalpern** [comment]
Actually the grep looks for the "empty" and omits the entire destructiveChanges.xml part of the command line options if it's empty, so while I don't think there would be any harm (I didn't test that), it absolutely omits it in that situation and I did test that part.

I agree re: the parsing hack, but in this case I tested a bunch, and it's pretty binary -- if the TYPES tag exists at all, there's at least one element to deploy (or undeploy). If not, the salesforce-git-delta tool generates XML with now TYPES tag. So I'm thinking at least for now, this'll work (and if we find a case that requires more advanced parsing, we can always add it later)

**Review by ricka — APPROVED** [review]
👍 sounds good to me!

**Pull request merged**
